# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8860584749546aa7121a8ba6df158154edd61f5e96fc91a857146ae1530aa5ab4c698adfbf2abad8cf99d299726a3bba04cc97593012b1e7f5f7b1569a356a39

test:
  secret_key_base: 415393f8dbdf46b9af73e32b191363ea4777b8a42acb12d40298ef1020e0aa111e331ba57a5569d0783125c773dff996e769471add865c69d8bba82e9ffe933c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
